[project]
name = "fly-in"
version = "0.1.0"
description = "Multiple Agent Path Finding project. Theme: Drones. Visual display theme: Genshin Impact"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "mypy>=2.3.1",
    "pygame-ce>=2.5.8",
]

[tool.flake8]
extend-exclude = [
    ".venv/",
]
